### ISSUE TITLE
Lucky::Params does not support query param or form data with array of values

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky#1380]
**Describe the bug**

To submit a query param with an array of values, it would look like: `?name=sally&name=john`. Crystal's `HTTP::Params` can parse this into an array

```crystal
params = HTTP::Params.parse("name=sally&name=john")
params.fetch_all("name") #=> ["sally", "john"]
params.fetch("name") #=> "sally" (only the first value)
```

The problem is that a lot of the methods on `HTTP::Params` only pulls the first value. The method we call on it in almost every situation is `#to_h` which only returns a `Hash(String, String)` which means it's only the first value of any query param.

**Expected behavior**

We need to provide some way to retrieve these query param array values.

**Comment by matthewmcgarvey** [comment]
Related to https://github.com/luckyframework/avram/issues/408

**Comment by stephendolan** [comment]
I actually think there are more options than repeating the same parameter, if it's helpful!

For example, in Rails if I wanted to send an array of IDs to a route, I'd use `?ids[]=1025&ids[]=1027` rather than `?ids=1025&ids=1027`.

Again, not sure if this would actually help with resolving the issue, but it'd at least make them more easily identifiable.

**Comment by matthewmcgarvey** [comment]
@stephendolan Those are actually the same. If you look at generated forms that will make an array, the name of the input is `ids[]` so if Crystal's `HTTP::Params` was given that, the values could be fetched with a key of `ids[]`.  You're right though that is is a Rails convention to name them in that way and we might consider doing the same.

**Comment by matthewmcgarvey** [comment]
Same goes for form data https://github.com/luckyframework/lucky/blob/80fa91ee0d2abd03093dc4830323e30a8097bd49/src/lucky/params.cr#L469-L476

**Comment by jwoertink** [comment]
One tricky part to this is that there's no actual RFC on how to handle arrays in params. It's basically up to each library to determine that. With that said, we do have `params.many_nested` already.

https://github.com/luckyframework/lucky/blob/80fa91ee0d2abd03093dc4830323e30a8097bd49/src/lucky/params.cr#L259-L268

**Comment by robacarp** [comment]
Yeah, the RFC on http query params is a mess. Lucky currently relies on a small suite of rails frontend tech that is co-opted from rails-ujs. Does adopting the rails convention of array parameters help us play nice with their front end utilities?

**Comment by matthewmcgarvey** [comment]
Here's some specifications I'm thinking about:

## Query Params and Form Data

- Single Param - name=john
- Nested Param - user:name=john
- Many Params - names[]=john
- Many Nested Params - users[0]:name=john

## API (unifies query params, form data, path variables, and json body)

- `#get?`
  - returns the value of a single param
  - returns nil if param missing
  - raises if param is malformed
  - returns first value if there are many params
  - returns value from first source that has value (if path variable with name it returns it and doesn't look in other places)
- `#get_all?`
  - returns single value in list if single param
  - returns nil if param missing
  - raises if param is malformed
  - returns all values if there are many params
  - returns values from first source that has any (if path variable with name it returns it and doesn't look in other places)
  - given a key, it appends `[]` to it when searching query params and form data

## TODO

- [ ] Update form data parsing to handle multiple values for the same key
- [ ] Add `#get_all?` and `#get_all` methods
- [ ] Updates to make sure form inputs and query params get the `[]` added to them when allowing multiple input (not sure what these changes are)

Any changes or additions I should make to this?

**Comment by jwoertink** [comment]
I think `get_all?` should always return an array so "returns single value in list if single param" would be `[thing]` instead of `thing`. It's always an array or nil.

As a side thought... what if our param parsing just converted params in to json, then the lookup methods just did a json lookup? In this case, the client sends the server some params, the server figures out if it's query, or body, or multi-part form params (skipping path params because that gets handled differently), and then converts it to json. If the client sends a json body, then there's no conversion needed. Just parse the json and you're good. If the client sends any other format, as long as it can be converted to json, then it'll fit in. 🤔

**Comment by matthewmcgarvey** [comment]
@jwoertink The only scenario I can think of that wouldn't work with that would be file uploads

**Comment by robacarp** [comment]
@matthewmcgarvey that's a good list. 

> returns value from first source that has value (if path variable with name it returns it and doesn't look in other places)

What do you mean by "from first source that has value"? Are you referring to nested params?

--- 

I'm thinking about this situation: `url?user[]:name=rob&user[]:password=secrets` -- that's a bastardization of the format you've given, but what does the backend then provide? Two users, one with a name and the other with a password? Or is this an invalid state and an exception is thrown?

**Comment by matthewmcgarvey** [comment]
@robacarp By source I mean the various things we are wrapping: path variables, query params, form data, and json. So if you call "name" and name is a path variable and in the json it would only return the path variable because it is the first place we check. This is not a change to how `Lucky::Params` work, I was only making explicit what it already does
